// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntvpatckjaqkfozizszm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dnBhdGNramFxa2Zveml6c3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDM5MDQsImV4cCI6MjA3MTUxOTkwNH0.r-EU8bZsnDIMDOoZMKZAm8B5feDcxAYSM1yMvjAbnw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Function to get current session token from localStorage
const getSessionToken = () => {
  const sessionToken = localStorage.getItem('app_session_token');
  const expiresAt = localStorage.getItem('app_session_expires');
  
  if (sessionToken && expiresAt) {
    const now = new Date();
    const expiry = new Date(expiresAt);
    
    if (now < expiry) {
      return sessionToken;
    }
  }
  
  return null;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: (input: RequestInfo | URL, init?: RequestInit) => {
      // Check if this is an edge function call
      const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
      const isEdgeFunction = url.includes('/functions/v1/');
      
      // Only add session token for non-edge-function requests
      if (!isEdgeFunction) {
        const token = getSessionToken();
        const headers = new Headers(init?.headers || {});
        if (token) headers.set('X-Session-Token', token);
        return fetch(input, { ...init, headers });
      }
      
      // For edge functions, use default fetch without modification
      return fetch(input, init);
    }
  }
});