// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntvpatckjaqkfozizszm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dnBhdGNramFxa2Zveml6c3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NDM5MDQsImV4cCI6MjA3MTUxOTkwNH0.r-EU8bZsnDIMDOoZMKZAm8B5feDcxAYSM1yMvjAbnw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Function to get current session token from localStorage
const getSessionToken = () => {
  const sessionToken = localStorage.getItem('app_session_token');
  const expiresAt = localStorage.getItem('app_session_expires');
  
  if (sessionToken && expiresAt) {
    const now = new Date();
    const expiry = new Date(expiresAt);
    
    if (now < expiry) {
      return sessionToken;
    }
  }
  
  return null;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      // Add session token to all requests
      get 'X-Session-Token'() {
        return getSessionToken() || '';
      }
    }
  }
});